Added Unicode scalar hex escapes (\u{1F913} for 🤓) to string syntax
cbor-wg/edn-literal pull request #28
Opened 2024-01-25 17:53 UTC by cabo

2024-01-25 18:09 UTC, hildjj requested changes

2024-01-25 18:09 UTC, hildjj commented on cbor-diag-parser.abnf
> +hexchar         = "{" *"0" hexscalar "}"
`*"0"` doesn't feel right.  Do you want `\u{00000000000001}` to be valid?  Maybe roll this into hexscalar for each alternative, bringing each up to a max of 6 characters.

2024-01-25 18:09 UTC, hildjj commented on cbor-diag-parser.abnf
> +hexscalar       = "10" 4HEXDIG / HEXDIG1 4HEXDIG / non-surrogate / 0*3HEXDIG
`\u{}` should not be valid, so this should be `1*3HEXDIG`, I think.

2024-01-26 10:12 UTC, cabo commented on cbor-diag-parser.abnf
> +hexchar         = "{" *"0" hexscalar "}"
Well, \U00001234 is quite common in other languages, so six is probably not making it too easy to convert that.
But this seems to be a stylistic thing anyway, I'd say; there is no specific artificial limit that can obviously agreed on.

Background is that I'm trying to keep this PEG-compatible, and there is only so much that can be achieved in the syntax.  I was trying to ensure surrogates trip the grammar, and that has priority I think.

2024-01-26 10:13 UTC, cabo commented on cbor-diag-parser.abnf
> +hexscalar       = "10" 4HEXDIG / HEXDIG1 4HEXDIG / non-surrogate / 0*3HEXDIG
Another PEG compatibility thing.  The 0 is eaten by the greedy `*"0"`, and to properly disallow `\u{}` this needs two more lines.  Oh well.

2024-01-26 16:03 UTC, hildjj approved these changes

2024-01-26 16:14 UTC, merged