Mention zone identifiers (ip'' supports them only indirectly)
cbor-wg/edn-literal pull request #63
Opened 2024-08-22 08:46 UTC by cabo

Close #62
(Thanks, Rohan!)

2024-08-22 08:53 UTC, cabo commented
@rohanmahy Sorry, my github fu is too weak to assign you as a reviewer.

2024-08-22 13:52 UTC, rohanmahy requested changes

2024-08-22 13:52 UTC, rohanmahy commented on draft-ietf-cbor-edn-literals.md
> +This can be represented as in `52([ip'192.0.2.42',24])`, if needed.
I would keep the sentence about zoneinfo separate (for which there is no defined encoding), from the sentence about prefix lengths.

Regarding the use of prefixes, I would have expected that ip'192.0.2.42/27' meant a host address of 192.0.2.43 with a mask of 255.255.255.224, however it seems that you mean to only use the /prefix notation for networks. If this is the case, I would continue the paragraph with text such what I wrote below.

```suggestion
Note that there is no direct representation of the "Interface format"
defined in {{Section 3.1.3 of -iptag}}.
An IP address with prefix in this app-string format represents an entire IP subnet, not a
specific host IP address and its mask/prefix. An Interface format (host IP address combined with an
optional prefix length and/or optional zone ID) can be represented as in the examples `52([ip'192.0.2.42',27])`, `54([ip'2001:54::b8:82ae:a7c:1234', 64], or `54([ip'fe80::82ae:a7c:1234', null, 'eth2'] , if needed.
```

2024-08-22 16:51 UTC, cabo commented on draft-ietf-cbor-edn-literals.md
> +This can be represented as in `52([ip'192.0.2.42',24])`, if needed.
The point of edn-literal is to provide a notation for tags, not to provide additional documentation for the tags, restating what already is on the definition of a tag.
[Restatements are bad][1].
(And, as I said, I don't want to include an example for zone identifiers here, because it is not the job of this document to meddle with the one identifiers in 9164.)

[1]: https://www.ietf.org/archive/id/draft-bormann-restatement-01.html#name-perils-of-restatements

2024-08-22 17:32 UTC, rohanmahy commented on draft-ietf-cbor-edn-literals.md
> +This can be represented as in `52([ip'192.0.2.42',24])`, if needed.
>The point of edn-literal is to provide a notation for tags
?? I thought the point of edn-literal was to describe a human-readable notation for CBOR (including tags). 

The subtlety of the difference between 192.0.2.42/27 (interface format) not representable in an ip app-string and 192.0.2.32/27 (prefix) representable in an ip app-string will be lost on most readers. It is essential to call this out in the description of the app-string.

Examples are good. They help implementers. You had an example in your text. I just added 2 additional examples.

2024-08-23 16:34 UTC, cabo commented
Merging this now as a basis for an editorial attempt.
As the discussion is not yet completed (https://github.com/cbor-wg/edn-literal/pull/63#discussion_r1727104056), Issue #62 to be reopened.

2024-08-23 16:34 UTC, merged